name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit & Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14,16,18]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Run Jest (parallel)
        run: npm run test:ci

      - name: Enforce coverage thresholds
        run: npm run coverage:check

  e2e-smoke:
    name: E2E Smoke Tests
    needs: unit-tests
    if: github.event_name != 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start app
        run: npm run start:ci &

      - name: Run Cypress headless
        run: npx cypress run --headless

  mutation-tests:
    name: Nightly Mutation Testing
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Stryker mutation tests
        run: npx stryker run
